
GET http://localhost:7777/api/v2/account-lists/1606135606732


###
GET http://localhost:7777/api/v2/account-lists/1606135606732


###
GET http://localhost:7777/api/v2/recipient-lists/1606135606732

###
POST http://localhost:7777/api/v2/recipient-lists/1606135606732 
content-type: application/json

{
    "number": "6546446465464",
    "name": "thaiia"
}

###

DELETE http://localhost:7777/api/v2/recipient-lists/1606135606732 
content-type: application/json

{
    "number": "6546446465464",
    "name": "thaiia"
}
###

PUT http://localhost:7777/api/v2/recipient-lists/1606135606732 
content-type: application/json

{
    "number": "2222222222",
    "name": "kim kim"
}


###
# checking account
GET http://localhost:7777/api/accounts/1606135606732 

###
# chuyển tiền
POST http://localhost:7777/api/v2/internal-transfer/1606135606732/1606142545882?typeTrans=transfer
content-type: application/json

{
    "mount": 20000,
    "detail": "chuyen tien",
    "sign": "djasdnaskdasj",
    "date": 8498434
}

###
GET http://localhost:7777/api/history/1606135606732?limit=10&page=2&typeTrans=receive


###
POST https://jsx-banking-app.herokuapp.com/api/login-recaptcha 

content-type: application/json

{
    "username": "jsxthai",
    "password": "123"
}
